### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by MoonDownHugo** [liusida/ComfyUI-AutoCropFaces#12]
!!! Exception during processing!!! not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "J:\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 3508, in image_paste_crop
    result_image, result_mask = self.paste_image(tensor2pil(image), tensor2pil(crop_image), crop_data, crop_blending, crop_sharpening)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 3546, in paste_image
    crop_size, (left, top, right, bottom) = crop_data
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by liusida** [comment]
Sorry, after upgrading the system to support batches, I didn't test the compatibility with WAS. I'll check later.

**Comment by MoonDownHugo** [comment]
Thank you very much for your hard work.

**Comment by Jojo-xqt** [comment]
> Sorry, after upgrading the system to support batches, I didn't test the compatibility with WAS. I'll check later.抱歉，在升级系统支持批处理后，我没有测试与 WAS 的兼容性。我稍后再检查。

期待您的更新，现在报错问题依然存在。

**Comment by liusida** [comment]
Sorry, I am traveling recently, and don't have the energy to fix this bug. Will there be anyone who can do a PR for this?
